name: Ubuntu and Mac builds

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_and_publish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pacakges
        run: python3 -m pip install --upgrade --upgrade-strategy eager twine cibuildwheel

      #- name: Build and Test 
      #  run: |
      #    python3 setup.py build_ext --inplace
      #    python3 -m unittest discover -v -s tests -p "test_*.py"

      - name: Build Wheels
        run: |
            python3 -m cibuildwheel --output-dir wheelhouse
            python3 setup.py sdist
            ls -lrt wheelhouse/*

      - uses: actions/upload-artifact@v2
        with:
          name: pygeoda-${{ matrix.os }}
          path: wheelhouse/

      - name: Check Release Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=publish::true
          fi

      - name: Publish to Pypi
        if: steps.check-tag.outputs.publish == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload wheelhouse/*.whl

      - name: Publish Source to Pypi
        if: matrix.os == 'macos-latest' && steps.check-tag.outputs.publish == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload dist/*.tar.gz