name: Ubuntu and Mac builds

on: push

jobs:
  build_and_publish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pacakges
        run: python3 -m pip install --upgrade --upgrade-strategy eager twine cibuildwheel

      - name: Build pygeoda 
        run: |
            python3 -m cibuildwheel --output-dir wheelhouse
            python3 setup.py sdist

      - name: Test pygeoda
        run: |
          ls -lrt wheelhouse/*
          pip3 install --no-index --find-links wheelhouse pygeoda
          python3 -m unittest discover -v -s tests -p "test_*.py"

      - name: Publish pygeoda
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m twine upload wheelhouse/*.whl
          python3 -m twine upload dist/*.tar.gz