# This is a basic workflow to help you get started with Actions

name: Windows builds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows_build:
    runs-on: ${{ matrix.config.os }}
    #if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, name: VS2017, python: 3.7, cc: cl, cxx: cl, platform: x64}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and Test
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel virtualenv
          python -m virtualenv venv
          venv\\Scripts\\activate
          python -c \"import sys; print(sys.executable)\"
          python setup.py build_ext --inplace
          python -m unittest discover -v -s tests -p \"test_*.py\"
